before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: W7py6GrKXIguwKsEi216DiybS6wSwQtSJz5pVJD4PbscInxQ1HGExhRWk2QDAw/UqDEWmdcJW+AsQR3r8Ah3/CyVVmWXubmVNQMM/va6cUMa4AdVkFwj26QJ90QkE/ntLtbOFbs8jE6TutCpq+An29vi1PVlKp8Oh5U7n07bjzF869EDt+q3LoAj5gIpUV+p1B/Wz/lnGyaRNt384Qi1rGrDsZwDNeO810DmBZVsxGzw4MVn1IYATu9/G02MOpIBURgj/W1ryuam46DdFDNFuJFESvweTVcqp4qimmSt9S5jiuqfODl19ms2bj0hOGYHKnY+0W62f6w+9I/BI/N6O0MBaiqjlepF62mo4oj9QWdJg31AgT2jiIuvz9lBBiYtq0t1xOAPZGNdbTe1BCbg6TocMzO6U53lnJ39yzmZpDKrDXWa0BjPQhWMiAaeLAWvqjmjh31TsnFuQGVPJqM/fPuN+7JDjK5M1/DhaPGU/EHdVuuJCrmIAdPHyOwXGpwvH8MHuy+rDg93PVAL3mF3SiNt8DiVXu26UYFTO0Zod4mk+4VcBIUw3OjBW07pQoZwXseOOxjtxDVhj6Dfb+WxM3gK6W3bo/iYdXB70K/SfpoJNjDOMgBySmw0VXlb/3LcektbEQG+V1LlHMCphpN9mobBXunUxG7gmI1UGCclB50= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
